[phases.setup]
aptPkgs = ["libxml2-dev", "libxslt-dev", "gcc", "g++", "python3-dev", "build-essential", "python3-setuptools", "python3-wheel"]
[phases.install]

[variables]
PIP_ONLY_BINARY = ":all:"
PIP_PREFER_BINARY = "1"
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"], "playwright install --with-deps chromium"

[start]
cmd = "python main.py"
